# Generated by Django 4.2 on 2024-01-04 05:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_remove_post_full_name_remove_post_phone_number_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Post",
        ),
    ]
