# Generated by Django 4.2.7 on 2024-01-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="temp_image/")),
                ("audio", models.FileField(upload_to="temp_audio/")),
            ],
        ),
        migrations.DeleteModel(
            name="GeneratedMusic",
        ),
        migrations.DeleteModel(
            name="ImageCaptioning",
        ),
    ]
