# Generated by Django 4.2 on 2024-01-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_generatedcontent_delete_generatedmusic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcontent",
            name="username",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
