# Generated by Django 4.2.7 on 2024-01-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_generatedcontent_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedcontent",
            name="image_name",
            field=models.CharField(default="None", max_length=255),
        ),
    ]
