# Generated by Django 4.2.7 on 2024-01-10 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_editedvideo"),
    ]

    operations = [
        migrations.AddField(
            model_name="editedvideo",
            name="video_name",
            field=models.CharField(default="None", max_length=255),
        ),
        migrations.AlterField(
            model_name="editedvideo",
            name="video_file",
            field=models.FileField(upload_to="mixed_video/"),
        ),
    ]
