# Generated by Django 4.2.7 on 2024-01-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CameraImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="webcam_image/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_deleted", models.BooleanField(default=True)),
            ],
        ),
    ]
