# Generated by Django 4.2.8 on 2024-01-05 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_generatedcontent_username'),
        ('boards', '0002_post_music_file_post_user_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='music_file',
        ),
        migrations.AddField(
            model_name='post',
            name='music_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.generatedcontent'),
            preserve_default=False,
        ),
    ]
